name: Linting

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add git safe directory
      run: git config --global --add safe.directory $(realpath .)

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.22.1'

    - name: Install APR
      run: |
        sudo apt update -y
        sudo apt install -y libapr1 libapr1-dev
      shell: bash

    - name: Install clang-tidy
      run: |
        curl -fsSL "https://apt.llvm.org/llvm-snapshot.gpg.key" | \
            gpg --dearmor | \
            sudo tee /usr/share/keyrings/llvm-snapshot-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/llvm-snapshot-keyring.gpg] http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main" | \
            sudo tee /etc/apt/sources.list.d/llvm.list
        apt update
        apt install -y clang-tidy-14
        sudo ln -s /usr/bin/clang-tidy-14 /usr/bin/clang-tidy
      shell: bash

    - name: Install dependencies of telebot
      run: |
        sudo apt update -y
        sudo apt install -y git pkg-config libjson-c-dev libcurl
      shell: bash


    - name: Cofnigure Cmake
      run: |
        bash scripts/build.sh configure
      shell: bash

    - name: Run clang-tidy
      run: |
        bash scripts/checks.sh lint
      shell: bash
