name: Linting

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add git safe directory
      run: git config --global --add safe.directory $(realpath .)

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.22.1'

    - name: Install APR
      run: |
        sudo apt update -y
        sudo apt install -y libapr1 libapr1-dev
      shell: bash

    - name: Install clang-tidy
      run: |
        sudo apt install clang-tidy
      shell: bash

    - name: Cofnigure Cmake
      run: |
        bash scripts/build.sh configure
      shell: bash

    - name: Run clang-tidy
      run: |
        bash scripts/checks.sh lint
      shell: bash
