# run all pre-commit hooks
name: Pre-commit

on:
  push:
    branches:
        - '**'
  pull_request:
    branches:
        - '**'

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3

    - name: Add git safe directory
      run: git config --global --add safe.directory $(realpath .)

    - name: Install pre-commit
      run: pip3 install pre-commit

    - name: Run pre-commit
      run: pre-commit run --all-files
